### ISSUE TITLE
Replace `VacuousValidation` with `Infallible`?

### ISSUE THREAD

**Issue by chpio** [rust-crdt/rust-crdt#105]
Hi, can we replace `VacuousValidation` with [`Infallible`](https://doc.rust-lang.org/std/convert/enum.Infallible.html)? Or is the `VacuousValidation` type deliberately unpublished or has a special meaning?

**Comment by davidrusu** [comment]
I wasn't aware of Infallible, it's a good suggestion. I'll replace it in the next release
