### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [rust-crdt/rust-crdt#129]
Newest release at crates.io is 7.1.0, yet this git repo has only tagged 7.0.0 from a year ago.

Please tag cargo releases in git - that helps correlating distributed code with source development.

**Comment by jonassmedegaard** [comment]
I notice that newest release at crates.io is now 7.2.0 - please tag releases here in git as well.

**Comment by davidrusu** [comment]
Done, added a 7.2.0 release: https://github.com/rust-crdt/rust-crdt/releases/tag/7.2.0

Thanks for the reminder
