### ISSUE TITLE
move project to organization

### ISSUE THREAD

**Issue by spacejam** [rust-crdt/rust-crdt#26]
I've moved the project to its own organization, and I've given @davidrusu an invite to the `owners` group and `crate-publishers` team, which can publish new crates!

Let me know if you have any questions or anything, but in general I totally trust you to make good decisions for the project :)

I'll still be here, and may want to add some features every once in a blue moon, but I'll coordinate with you first, since this is your thing as well!

**Comment by davidrusu** [comment]
Nice! 🚀
