### ISSUE TITLE
reset_remove.rs example fails

### ISSUE THREAD

**Issue by dirvine** [rust-crdt/rust-crdt#33]
The final assert in this example fails. I am not 100% up to speed yet, but I am not certain the deferred() in the output of the ORSWATS via println! is related. I did try and make `apply_deferred` public and run that, but it did make no difference (as I would expect). 

Anyhow the example seems slightly confusing and asserts so it needs some attention I think. I will not PR here yet until U fully understand the ORSWAT impl (especially if deferred is part of the impl as I am not sure why/how this is being used).

**Comment by davidrusu** [comment]
@dirvine I've opened up a few issues to address this properly, I'm really not sure how I did not catch this earlier but I've tracked the problem down and implemented a fix in https://github.com/rust-crdt/rust-crdt/pull/36/files#diff-178822c448ce6afe0e383be6f514626eR166. 

That whole section of code is too complex for my liking, I'll see about doing some cleanup soon.

(and note taken on the example being confusing, I'll make an attempt to simplify it as well)
