### ISSUE TITLE
Feature Request: Method to obtain ReadCtx without copying any data

### ISSUE THREAD

**Issue by pnehrer** [rust-crdt/rust-crdt#56]
I would like to be able to get a ReadCtx from a CRDT without any particular value.

E.g., in order to add an element to an Orswot I first have to `read()` it, which involves copying all elements into a new HashSet, or check if it `contains()` an element, which involves checking the HashSet contains, but in both cases I don't care about ReadCtx.val; only the clocks.

Would it make sense to add something like

```
fn read_ctx() -> ReadCtx<(), A>;
```

to Orswot in particular, or even other non-trivial CRDTs?

**Comment by davidrusu** [comment]
Makes a lot of sense to me, both the `rm_clock` and the `add_clock` inside the `ReadCtx` would be the same top level CRDT clock. :+1: 

Want to take a stab at an implementation?

It would make sense for every `Causal` CRDT to have this function as part of it's interface, I'd start by adding it to the `Causal` trait in `src/traits.rs`

**Comment by hjorvari** [comment]
(this one too btw)

**Comment by davidrusu** [comment]
Thanks
