### ISSUE TITLE
Feature Request: Support addition and removal of multiple Orswot members at a time

### ISSUE THREAD

**Issue by pnehrer** [rust-crdt/rust-crdt#57]
In some use-cases I would like to be able to add/remove multiple members to/from an Orswot at a time. It seems that Op::Rm already tracks multiple members and Op::Add (and the corresponding apply logic) could be adapted as well to apply the actor's dot to each individual member's clock.

Do you think this would cause any unforeseen problems?

Happy to submit a PR if interested.

**Comment by davidrusu** [comment]
I think this should work, please do submit a PR!

**Comment by hjorvari** [comment]
this issue can be closed no?

**Comment by davidrusu** [comment]
@hjorvari yep 👍
