### ISSUE TITLE
Sequence CRDTs

### ISSUE THREAD

**Issue by xldenis** [rust-crdt/rust-crdt#58]
Hi,

I've been implementing a version of LSEQ focused on correctness (I've found bugs in every OSS implementation so far :/). Would there be any interest in having it merged into this library? 

I still need to rewrite the id generation code to more cleanly integrate all the fixes to all the bugs I discovered along the way and write more property tests, but once that's done I can prepare a PR.

**Comment by davidrusu** [comment]
A good sequence CRDT would be a very welcome addition to the library. I'll be happy to look at a PR once you have it one up.

**Comment by xldenis** [comment]
Now that I've finished exams, I've started moving my implementation of LSeq over to a [fork](https://github.com/xldenis/rust-crdt) of this crate. I still need to do some clean ups, as well as write docs and more property tests. But it should be good to look over by the end of the week!

PS: I added a dependency on `rand` as well as on `bitvec` which are required to properly generate identifiers for LSeq trees.

**Comment by davidrusu** [comment]
@xldenis Looking forward to reading over the implementation once it's finished baking! No worries on the extra dependency side, if it's needed, bring it in.

It would be nice to have an implementation of `Version Vector with Exceptions` with this work if it's needed for LSeq, it would be nice to have all CRDT related dependencies in the repo itself.  

That said, if you want to implement this `Version Vector with Exceptions` in a crate you maintain and bring it in the dependency to rust-crdt's that's cool too :)

**Comment by xldenis** [comment]
I'll see what I do with the VVwE, it's not _strictly_ necessary for an LSeq it just allows you to restore a causal order if you don't already have one.

**Comment by FintanH** [comment]
Hey @xldenis :wave: Any work in progress I can look at and/or help with? :grin: I'm eager to have a vector/sequence-like CRDT for an implementation I want to work on!

**Comment by xldenis** [comment]
yep! sorry I've been meaning to post an update! Let me push my changes. The main thing missing are more property tests :)

**Comment by FintanH** [comment]
Well I do love using correct code, so I'm at your services if you need some help there :grin:

**Comment by xldenis** [comment]
There is one thing that could be very nice, especially for network transfer. Writing an encoder/decoder from `Identifier` to `BigNum` it should enable a significantly smaller size for messages!

**Comment by xldenis** [comment]
I think this issue can be closed for now :)
