### ISSUE TITLE
Trait Bounds

### ISSUE THREAD

**Issue by FintanH** [rust-crdt/rust-crdt#63]
Hey! :wave:

I've just picked up your library to implement a [convergent issue tracker](https://radicle.community/t/coco-jammin-on-dags/140) and it's been nice to work with so far. So thank you for providing such a useful crate in the Rust ecosystem :grin: 

What I wanted to bring up was that the bounds imposed on stuff like `mvreg::Val`, i.e `Debug` and `Clone` seem very restrictive. I've cloned the repo locally and tried removing them. `Debug` wasn't used anywhere and `Clone` is only used on a few of the functions. 

I think it might be better to localise the trait bounds where they are needed rather than have blanket bounds. This localises the needs for the traits indicating to the caller _when_ they are needed. Maybe they don't even need the bound in the first place :man_shrugging: 

Just wanted to get your thoughts on this and ask would you mind a pull request that included these changes?

**Comment by davidrusu** [comment]
Very fitting issue, I was just running into this issue myself :)

Yes, you're right, these trait bounds are not needed generally. I have a quality of life improvement PR up in #65 that may include this relaxation. Otherwise also happy to take a PR as well.

**Comment by davidrusu** [comment]
Oh! I'm blind! I see you PR is right there on #64 taking a look now

**Comment by davidrusu** [comment]
fixed in #64
