### ISSUE TITLE
Vector-like CRDT

### ISSUE THREAD

**Issue by FintanH** [rust-crdt/rust-crdt#70]
I wanted to check if there might be some known state of the art for a vector-like CRDT.

I believe what I want is a grow-only vector where I can also edit the items using an index. I started playing around with the concept of a grow-only vector using [sorted-vec](https://docs.rs/sorted-vec/0.3.6/sorted_vec/struct.SortedVec.html). This seemed to work and make sense as a CvRDT. It covers the case of creating a new vector and inserting based on ordering. Introducing editing, however, would mean that I need a CmRDT. 

Does this make sense? Have you heard of something like this? And would someone like to help implement this with me? :grin:

**Comment by FintanH** [comment]
Oh also, I think since editing at an index would be an operation, the values would need to be CRDTs themselves as well.

**Comment by davidrusu** [comment]
I think @xldenis has been working on something that may fit your needs in #58. I'm not sure how close that work is to merging, perhaps you can help on that front?

**Comment by xldenis** [comment]
Now that #74 is merged, this can be closed i think.

**Comment by FintanH** [comment]
Thanks @xldenis :) Closing it now :+1:
