### ISSUE TITLE
Add a license ?

### ISSUE THREAD

**Issue by abour** [rust-crdt/rust-crdt#78]
Hi this library seems very nice.
I would like to know how it is licensed (and add the license file ?)

**Comment by chpio** [comment]
> license = "Apache-2.0"

in the cargo file. But yeah a "real" license file would be nicer.

**Comment by abour** [comment]
Ok thank you !

I added a pull request if wished.
https://github.com/rust-crdt/rust-crdt/pull/79

**Comment by davidrusu** [comment]
closed in #79
