### ISSUE TITLE
LSEQ Dot counter is 0-based in operations

### ISSUE THREAD

**Issue by bochaco** [rust-crdt/rust-crdt#86]
@davidrusu , I'm not fully sure, but I'm trying to use the Dot of each LSEQ operation to populate a VClock that I'm planning to use as a context. 

When I get the Dot from the very first append op on an LSEQ its counter is 0, so when I want to compare that with the context, where this op didn't happen, (using `VClock::partial_cmp`) they happen to be `Equal`. Thus, shouldn't the Dot's counter of the very first op be 1 instead of 0?

**Comment by davidrusu** [comment]
Hey @bochaco yeah your right, the empty lseq should have the implicit count of 0, any mutations to the empty lseq should increase the counter.

(Apologies for the delay in response, somehow did not get this notification)

**Comment by bochaco** [comment]
ah right, cool, no worries, I can add a fix to PR #85 if you then agree with this

**Comment by davidrusu** [comment]
@bochaco I've already merged #85! but yes a new PR would be very welcome

**Comment by bochaco** [comment]
ahh too late it's merged :D I'll send a separate PR.
