### ISSUE TITLE
LWWReg: Why are timestamps bad?

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [rust-crdt/rust-crdt#95]
The documentation for `crdts::lwwreg::LWWReg` mentions not to use timestamps "unless you are comfortable with divergence" without explaining why.

But to me, timestamps are a fairly obvious way of determining the "last" write. If they are precise enough, you should never have an equal timestamp (and if they do happen to be equal, you could probably just choose arbitrary).

Is there something I'm not seeing here that would cause timestamps to be more of an issue?

**Comment by mohe2015** [comment]
WIthout knowing much I think that it's easy to manipulate them and it's not always easy to synchronize them properly. But I also don't know much more.

**Comment by davidrusu** [comment]
You need to ensure all actors make the same choice, independent of the order they receive updates.

> and if they do happen to be equal, you could probably just choose arbitrary

arbitrary sure, but just make sure it's deterministic, you need to ensure all actors make the same choice.

I recommend imposing a total order over your actors, then use the two tuple `(timestamp, actor)` with the natural ordering as your LWW marker. The `Actor` id is globally unique and will act as a tie breaker.

**Comment by ColonelThirtyTwo** [comment]
@davidrusu That makes sense. I'd recommend expanding the documentation with that info.
